//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Inventario {

    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable ()]
    [global::System.ComponentModel.DesignerCategoryAttribute ("code")]
    [global::System.ComponentModel.ToolboxItem (true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute ("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute ("DataSet1")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute ("vs.data.DataSet")]
    public partial class DataSet1 : global::System.Data.DataSet {

        private consultarVentasDataTable tableconsultarVentas;

        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DataSet1 () {
            this.BeginInit ();
            this.InitClass ();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler (this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit ();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DataSet1 (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context):
            base (info, context, false) {
                if ((this.IsBinarySerialized (info, context) == true)) {
                    this.InitVars (false);
                    global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler (this.SchemaChanged);
                    this.Tables.CollectionChanged += schemaChangedHandler1;
                    this.Relations.CollectionChanged += schemaChangedHandler1;
                    return;
                }
                string strSchema = ((string) (info.GetValue ("XmlSchema", typeof (string))));
                if ((this.DetermineSchemaSerializationMode (info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                    global::System.Data.DataSet ds = new global::System.Data.DataSet ();
                    ds.ReadXmlSchema (new global::System.Xml.XmlTextReader (new global::System.IO.StringReader (strSchema)));
                    if ((ds.Tables["consultarVentas"] != null)) {
                        base.Tables.Add (new consultarVentasDataTable (ds.Tables["consultarVentas"]));
                    }
                    this.DataSetName = ds.DataSetName;
                    this.Prefix = ds.Prefix;
                    this.Namespace = ds.Namespace;
                    this.Locale = ds.Locale;
                    this.CaseSensitive = ds.CaseSensitive;
                    this.EnforceConstraints = ds.EnforceConstraints;
                    this.Merge (ds, false, global::System.Data.MissingSchemaAction.Add);
                    this.InitVars ();
                } else {
                    this.ReadXmlSchema (new global::System.Xml.XmlTextReader (new global::System.IO.StringReader (strSchema)));
                }
                this.GetSerializationData (info, context);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler (this.SchemaChanged);
                base.Tables.CollectionChanged += schemaChangedHandler;
                this.Relations.CollectionChanged += schemaChangedHandler;
            }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable (false)]
        [global::System.ComponentModel.DesignerSerializationVisibility (global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public consultarVentasDataTable consultarVentas {
            get {
                return this.tableconsultarVentas;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute (true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute (global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute (global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute (global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet () {
            this.BeginInit ();
            this.InitClass ();
            this.EndInit ();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone () {
            DataSet1 cln = ((DataSet1) (base.Clone ()));
            cln.InitVars ();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables () {
            return false;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations () {
            return false;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable (global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode (reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset ();
                global::System.Data.DataSet ds = new global::System.Data.DataSet ();
                ds.ReadXml (reader);
                if ((ds.Tables["consultarVentas"] != null)) {
                    base.Tables.Add (new consultarVentasDataTable (ds.Tables["consultarVentas"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge (ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars ();
            } else {
                this.ReadXml (reader);
                this.InitVars ();
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable () {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream ();
            this.WriteXmlSchema (new global::System.Xml.XmlTextWriter (stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read (new global::System.Xml.XmlTextReader (stream), null);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars () {
            this.InitVars (true);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars (bool initTable) {
            this.tableconsultarVentas = ((consultarVentasDataTable) (base.Tables["consultarVentas"]));
            if ((initTable == true)) {
                if ((this.tableconsultarVentas != null)) {
                    this.tableconsultarVentas.InitVars ();
                }
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass () {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSet1.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableconsultarVentas = new consultarVentasDataTable ();
            base.Tables.Add (this.tableconsultarVentas);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeconsultarVentas () {
            return false;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged (object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars ();
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema (global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSet1 ds = new DataSet1 ();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType ();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence ();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny ();
            any.Namespace = ds.Namespace;
            sequence.Items.Add (any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable ();
            if (xs.Contains (dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream ();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream ();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write (s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas (dsSchema.TargetNamespace).GetEnumerator (); schemas.MoveNext ();) {
                        schema = ((global::System.Xml.Schema.XmlSchema) (schemas.Current));
                        s2.SetLength (0);
                        schema.Write (s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (;
                                ((s1.Position != s1.Length) &&
                                    (s1.ReadByte () == s2.ReadByte ()));) {;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                } finally {
                    if ((s1 != null)) {
                        s1.Close ();
                    }
                    if ((s2 != null)) {
                        s2.Close ();
                    }
                }
            }
            xs.Add (dsSchema);
            return type;
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void consultarVentasRowChangeEventHandler (object sender, consultarVentasRowChangeEvent e);

        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable ()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute ("GetTypedTableSchema")]
        public partial class consultarVentasDataTable : global::System.Data.TypedTableBase<consultarVentasRow> {

            private global::System.Data.DataColumn columnnumero_factura;

            private global::System.Data.DataColumn columnfecha;

            private global::System.Data.DataColumn columntotal;

            private global::System.Data.DataColumn columnnombre_cliente;

            private global::System.Data.DataColumn columncodigo_cliente;

            private global::System.Data.DataColumn columnsexo;

            private global::System.Data.DataColumn columncodigo_producto;

            private global::System.Data.DataColumn columnnombre_producto;

            private global::System.Data.DataColumn columncantidad_vendida;

            private global::System.Data.DataColumn columnprecio_de_venta;

            private global::System.Data.DataColumn columnimporte;

            private global::System.Data.DataColumn columncodigo_departamento;

            private global::System.Data.DataColumn columnnombre_departamento;

            private global::System.Data.DataColumn columnnombre_unidad;

            private global::System.Data.DataColumn columnnombre_suplidor;

            private global::System.Data.DataColumn columnestado;

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public consultarVentasDataTable () {
                this.TableName = "consultarVentas";
                this.BeginInit ();
                this.InitClass ();
                this.EndInit ();
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal consultarVentasDataTable (global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString () != table.DataSet.Locale.ToString ())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected consultarVentasDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base (info, context) {
                this.InitVars ();
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn numero_facturaColumn {
                get {
                    return this.columnnumero_factura;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fechaColumn {
                get {
                    return this.columnfecha;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn totalColumn {
                get {
                    return this.columntotal;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_clienteColumn {
                get {
                    return this.columnnombre_cliente;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_clienteColumn {
                get {
                    return this.columncodigo_cliente;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sexoColumn {
                get {
                    return this.columnsexo;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_productoColumn {
                get {
                    return this.columncodigo_producto;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_productoColumn {
                get {
                    return this.columnnombre_producto;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn cantidad_vendidaColumn {
                get {
                    return this.columncantidad_vendida;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn precio_de_ventaColumn {
                get {
                    return this.columnprecio_de_venta;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn importeColumn {
                get {
                    return this.columnimporte;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_departamentoColumn {
                get {
                    return this.columncodigo_departamento;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_departamentoColumn {
                get {
                    return this.columnnombre_departamento;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_unidadColumn {
                get {
                    return this.columnnombre_unidad;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_suplidorColumn {
                get {
                    return this.columnnombre_suplidor;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn estadoColumn {
                get {
                    return this.columnestado;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable (false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public consultarVentasRow this [int index] {
                get {
                    return ((consultarVentasRow) (this.Rows[index]));
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event consultarVentasRowChangeEventHandler consultarVentasRowChanging;

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event consultarVentasRowChangeEventHandler consultarVentasRowChanged;

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event consultarVentasRowChangeEventHandler consultarVentasRowDeleting;

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event consultarVentasRowChangeEventHandler consultarVentasRowDeleted;

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddconsultarVentasRow (consultarVentasRow row) {
                this.Rows.Add (row);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public consultarVentasRow AddconsultarVentasRow (System.DateTime fecha, float total, string nombre_cliente, string sexo, string nombre_producto, float cantidad_vendida, float precio_de_venta, float importe, string nombre_departamento, string nombre_unidad, string nombre_suplidor, bool estado) {
                consultarVentasRow rowconsultarVentasRow = ((consultarVentasRow) (this.NewRow ()));
                object[] columnValuesArray = new object[] {
                    null,
                    fecha,
                    total,
                    nombre_cliente,
                    null,
                    sexo,
                    null,
                    nombre_producto,
                    cantidad_vendida,
                    precio_de_venta,
                    importe,
                    null,
                    nombre_departamento,
                    nombre_unidad,
                    nombre_suplidor,
                    estado
                };
                rowconsultarVentasRow.ItemArray = columnValuesArray;
                this.Rows.Add (rowconsultarVentasRow);
                return rowconsultarVentasRow;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone () {
                consultarVentasDataTable cln = ((consultarVentasDataTable) (base.Clone ()));
                cln.InitVars ();
                return cln;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance () {
                return new consultarVentasDataTable ();
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars () {
                this.columnnumero_factura = base.Columns["numero_factura"];
                this.columnfecha = base.Columns["fecha"];
                this.columntotal = base.Columns["total"];
                this.columnnombre_cliente = base.Columns["nombre_cliente"];
                this.columncodigo_cliente = base.Columns["codigo_cliente"];
                this.columnsexo = base.Columns["sexo"];
                this.columncodigo_producto = base.Columns["codigo_producto"];
                this.columnnombre_producto = base.Columns["nombre_producto"];
                this.columncantidad_vendida = base.Columns["cantidad_vendida"];
                this.columnprecio_de_venta = base.Columns["precio_de_venta"];
                this.columnimporte = base.Columns["importe"];
                this.columncodigo_departamento = base.Columns["codigo_departamento"];
                this.columnnombre_departamento = base.Columns["nombre_departamento"];
                this.columnnombre_unidad = base.Columns["nombre_unidad"];
                this.columnnombre_suplidor = base.Columns["nombre_suplidor"];
                this.columnestado = base.Columns["estado"];
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass () {
                this.columnnumero_factura = new global::System.Data.DataColumn ("numero_factura", typeof (int), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnnumero_factura);
                this.columnfecha = new global::System.Data.DataColumn ("fecha", typeof (global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnfecha);
                this.columntotal = new global::System.Data.DataColumn ("total", typeof (float), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columntotal);
                this.columnnombre_cliente = new global::System.Data.DataColumn ("nombre_cliente", typeof (string), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnnombre_cliente);
                this.columncodigo_cliente = new global::System.Data.DataColumn ("codigo_cliente", typeof (int), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columncodigo_cliente);
                this.columnsexo = new global::System.Data.DataColumn ("sexo", typeof (string), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnsexo);
                this.columncodigo_producto = new global::System.Data.DataColumn ("codigo_producto", typeof (int), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columncodigo_producto);
                this.columnnombre_producto = new global::System.Data.DataColumn ("nombre_producto", typeof (string), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnnombre_producto);
                this.columncantidad_vendida = new global::System.Data.DataColumn ("cantidad_vendida", typeof (float), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columncantidad_vendida);
                this.columnprecio_de_venta = new global::System.Data.DataColumn ("precio_de_venta", typeof (float), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnprecio_de_venta);
                this.columnimporte = new global::System.Data.DataColumn ("importe", typeof (float), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnimporte);
                this.columncodigo_departamento = new global::System.Data.DataColumn ("codigo_departamento", typeof (int), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columncodigo_departamento);
                this.columnnombre_departamento = new global::System.Data.DataColumn ("nombre_departamento", typeof (string), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnnombre_departamento);
                this.columnnombre_unidad = new global::System.Data.DataColumn ("nombre_unidad", typeof (string), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnnombre_unidad);
                this.columnnombre_suplidor = new global::System.Data.DataColumn ("nombre_suplidor", typeof (string), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnnombre_suplidor);
                this.columnestado = new global::System.Data.DataColumn ("estado", typeof (bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add (this.columnestado);
                this.columnnumero_factura.AutoIncrement = true;
                this.columnnumero_factura.AutoIncrementSeed = -1;
                this.columnnumero_factura.AutoIncrementStep = -1;
                this.columnnumero_factura.AllowDBNull = false;
                this.columnnumero_factura.ReadOnly = true;
                this.columnnombre_cliente.MaxLength = 50;
                this.columncodigo_cliente.AutoIncrement = true;
                this.columncodigo_cliente.AutoIncrementSeed = -1;
                this.columncodigo_cliente.AutoIncrementStep = -1;
                this.columncodigo_cliente.AllowDBNull = false;
                this.columncodigo_cliente.ReadOnly = true;
                this.columnsexo.MaxLength = 50;
                this.columncodigo_producto.AutoIncrement = true;
                this.columncodigo_producto.AutoIncrementSeed = -1;
                this.columncodigo_producto.AutoIncrementStep = -1;
                this.columncodigo_producto.AllowDBNull = false;
                this.columncodigo_producto.ReadOnly = true;
                this.columnnombre_producto.MaxLength = 50;
                this.columnimporte.ReadOnly = true;
                this.columncodigo_departamento.AutoIncrement = true;
                this.columncodigo_departamento.AutoIncrementSeed = -1;
                this.columncodigo_departamento.AutoIncrementStep = -1;
                this.columncodigo_departamento.AllowDBNull = false;
                this.columncodigo_departamento.ReadOnly = true;
                this.columnnombre_departamento.MaxLength = 50;
                this.columnnombre_unidad.MaxLength = 50;
                this.columnnombre_suplidor.MaxLength = 50;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public consultarVentasRow NewconsultarVentasRow () {
                return ((consultarVentasRow) (this.NewRow ()));
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder) {
                return new consultarVentasRow (builder);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType () {
                return typeof (consultarVentasRow);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged (e);
                if ((this.consultarVentasRowChanged != null)) {
                    this.consultarVentasRowChanged (this, new consultarVentasRowChangeEvent (((consultarVentasRow) (e.Row)), e.Action));
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging (e);
                if ((this.consultarVentasRowChanging != null)) {
                    this.consultarVentasRowChanging (this, new consultarVentasRowChangeEvent (((consultarVentasRow) (e.Row)), e.Action));
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted (e);
                if ((this.consultarVentasRowDeleted != null)) {
                    this.consultarVentasRowDeleted (this, new consultarVentasRowChangeEvent (((consultarVentasRow) (e.Row)), e.Action));
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting (e);
                if ((this.consultarVentasRowDeleting != null)) {
                    this.consultarVentasRowDeleting (this, new consultarVentasRowChangeEvent (((consultarVentasRow) (e.Row)), e.Action));
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveconsultarVentasRow (consultarVentasRow row) {
                this.Rows.Remove (row);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType ();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence ();
                DataSet1 ds = new DataSet1 ();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny ();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal (0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add (any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny ();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal (1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add (any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute ();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add (attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute ();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "consultarVentasDataTable";
                type.Attributes.Add (attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable ();
                if (xs.Contains (dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream ();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream ();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write (s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas (dsSchema.TargetNamespace).GetEnumerator (); schemas.MoveNext ();) {
                            schema = ((global::System.Xml.Schema.XmlSchema) (schemas.Current));
                            s2.SetLength (0);
                            schema.Write (s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (;
                                    ((s1.Position != s1.Length) &&
                                        (s1.ReadByte () == s2.ReadByte ()));) {;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    } finally {
                        if ((s1 != null)) {
                            s1.Close ();
                        }
                        if ((s2 != null)) {
                            s2.Close ();
                        }
                    }
                }
                xs.Add (dsSchema);
                return type;
            }
        }

        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class consultarVentasRow : global::System.Data.DataRow {

            private consultarVentasDataTable tableconsultarVentas;

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal consultarVentasRow (global::System.Data.DataRowBuilder rb):
                base (rb) {
                    this.tableconsultarVentas = ((consultarVentasDataTable) (this.Table));
                }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int numero_factura {
                get {
                    return ((int) (this [this.tableconsultarVentas.numero_facturaColumn]));
                }
                set {
                    this [this.tableconsultarVentas.numero_facturaColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime fecha {
                get {
                    try {
                        return ((global::System.DateTime) (this [this.tableconsultarVentas.fechaColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'fecha\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.fechaColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public float total {
                get {
                    try {
                        return ((float) (this [this.tableconsultarVentas.totalColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'total\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.totalColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_cliente {
                get {
                    try {
                        return ((string) (this [this.tableconsultarVentas.nombre_clienteColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'nombre_cliente\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.nombre_clienteColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_cliente {
                get {
                    return ((int) (this [this.tableconsultarVentas.codigo_clienteColumn]));
                }
                set {
                    this [this.tableconsultarVentas.codigo_clienteColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sexo {
                get {
                    try {
                        return ((string) (this [this.tableconsultarVentas.sexoColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'sexo\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.sexoColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_producto {
                get {
                    return ((int) (this [this.tableconsultarVentas.codigo_productoColumn]));
                }
                set {
                    this [this.tableconsultarVentas.codigo_productoColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_producto {
                get {
                    try {
                        return ((string) (this [this.tableconsultarVentas.nombre_productoColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'nombre_producto\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.nombre_productoColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public float cantidad_vendida {
                get {
                    try {
                        return ((float) (this [this.tableconsultarVentas.cantidad_vendidaColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'cantidad_vendida\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.cantidad_vendidaColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public float precio_de_venta {
                get {
                    try {
                        return ((float) (this [this.tableconsultarVentas.precio_de_ventaColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'precio_de_venta\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.precio_de_ventaColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public float importe {
                get {
                    try {
                        return ((float) (this [this.tableconsultarVentas.importeColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'importe\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.importeColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_departamento {
                get {
                    return ((int) (this [this.tableconsultarVentas.codigo_departamentoColumn]));
                }
                set {
                    this [this.tableconsultarVentas.codigo_departamentoColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_departamento {
                get {
                    try {
                        return ((string) (this [this.tableconsultarVentas.nombre_departamentoColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'nombre_departamento\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.nombre_departamentoColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_unidad {
                get {
                    try {
                        return ((string) (this [this.tableconsultarVentas.nombre_unidadColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'nombre_unidad\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.nombre_unidadColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_suplidor {
                get {
                    try {
                        return ((string) (this [this.tableconsultarVentas.nombre_suplidorColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'nombre_suplidor\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.nombre_suplidorColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool estado {
                get {
                    try {
                        return ((bool) (this [this.tableconsultarVentas.estadoColumn]));
                    } catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException ("The value for column \'estado\' in table \'consultarVentas\' is DBNull.", e);
                    }
                }
                set {
                    this [this.tableconsultarVentas.estadoColumn] = value;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfechaNull () {
                return this.IsNull (this.tableconsultarVentas.fechaColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfechaNull () {
                this [this.tableconsultarVentas.fechaColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IstotalNull () {
                return this.IsNull (this.tableconsultarVentas.totalColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SettotalNull () {
                this [this.tableconsultarVentas.totalColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_clienteNull () {
                return this.IsNull (this.tableconsultarVentas.nombre_clienteColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_clienteNull () {
                this [this.tableconsultarVentas.nombre_clienteColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IssexoNull () {
                return this.IsNull (this.tableconsultarVentas.sexoColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetsexoNull () {
                this [this.tableconsultarVentas.sexoColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_productoNull () {
                return this.IsNull (this.tableconsultarVentas.nombre_productoColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_productoNull () {
                this [this.tableconsultarVentas.nombre_productoColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscantidad_vendidaNull () {
                return this.IsNull (this.tableconsultarVentas.cantidad_vendidaColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcantidad_vendidaNull () {
                this [this.tableconsultarVentas.cantidad_vendidaColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isprecio_de_ventaNull () {
                return this.IsNull (this.tableconsultarVentas.precio_de_ventaColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setprecio_de_ventaNull () {
                this [this.tableconsultarVentas.precio_de_ventaColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsimporteNull () {
                return this.IsNull (this.tableconsultarVentas.importeColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetimporteNull () {
                this [this.tableconsultarVentas.importeColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_departamentoNull () {
                return this.IsNull (this.tableconsultarVentas.nombre_departamentoColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_departamentoNull () {
                this [this.tableconsultarVentas.nombre_departamentoColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_unidadNull () {
                return this.IsNull (this.tableconsultarVentas.nombre_unidadColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_unidadNull () {
                this [this.tableconsultarVentas.nombre_unidadColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_suplidorNull () {
                return this.IsNull (this.tableconsultarVentas.nombre_suplidorColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_suplidorNull () {
                this [this.tableconsultarVentas.nombre_suplidorColumn] = global::System.Convert.DBNull;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsestadoNull () {
                return this.IsNull (this.tableconsultarVentas.estadoColumn);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetestadoNull () {
                this [this.tableconsultarVentas.estadoColumn] = global::System.Convert.DBNull;
            }
        }

        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class consultarVentasRowChangeEvent : global::System.EventArgs {

            private consultarVentasRow eventRow;

            private global::System.Data.DataRowAction eventAction;

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public consultarVentasRowChangeEvent (consultarVentasRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public consultarVentasRow Row {
                get {
                    return this.eventRow;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Inventario.DataSet1TableAdapters {

    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute ("code")]
    [global::System.ComponentModel.ToolboxItem (true)]
    [global::System.ComponentModel.DataObjectAttribute (true)]
    [global::System.ComponentModel.DesignerAttribute ("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute ("vs.data.TableAdapter")]
    public partial class consultarVentasTableAdapter : global::System.ComponentModel.Component {

        private global::System.Data.SqlClient.SqlDataAdapter _adapter;

        private global::System.Data.SqlClient.SqlConnection _connection;

        private global::System.Data.SqlClient.SqlTransaction _transaction;

        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;

        private bool _clearBeforeFill;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public consultarVentasTableAdapter () {
            this.ClearBeforeFill = true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected internal global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter ();
                }
                return this._adapter;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection ();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0;
                    (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand) (this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal global::System.Data.SqlClient.SqlTransaction Transaction {
            get {
                return this._transaction;
            }
            set {
                this._transaction = value;
                for (int i = 0;
                    (i < this.CommandCollection.Length); i = (i + 1)) {
                    this.CommandCollection[i].Transaction = this._transaction;
                }
                if (((this.Adapter != null) &&
                        (this.Adapter.DeleteCommand != null))) {
                    this.Adapter.DeleteCommand.Transaction = this._transaction;
                }
                if (((this.Adapter != null) &&
                        (this.Adapter.InsertCommand != null))) {
                    this.Adapter.InsertCommand.Transaction = this._transaction;
                }
                if (((this.Adapter != null) &&
                        (this.Adapter.UpdateCommand != null))) {
                    this.Adapter.UpdateCommand.Transaction = this._transaction;
                }
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection ();
                }
                return this._commandCollection;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitAdapter () {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter ();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping ();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "consultarVentas";
            tableMapping.ColumnMappings.Add ("numero_factura", "numero_factura");
            tableMapping.ColumnMappings.Add ("fecha", "fecha");
            tableMapping.ColumnMappings.Add ("total", "total");
            tableMapping.ColumnMappings.Add ("nombre_cliente", "nombre_cliente");
            tableMapping.ColumnMappings.Add ("codigo_cliente", "codigo_cliente");
            tableMapping.ColumnMappings.Add ("sexo", "sexo");
            tableMapping.ColumnMappings.Add ("codigo_producto", "codigo_producto");
            tableMapping.ColumnMappings.Add ("nombre_producto", "nombre_producto");
            tableMapping.ColumnMappings.Add ("cantidad_vendida", "cantidad_vendida");
            tableMapping.ColumnMappings.Add ("precio_de_venta", "precio_de_venta");
            tableMapping.ColumnMappings.Add ("importe", "importe");
            tableMapping.ColumnMappings.Add ("codigo_departamento", "codigo_departamento");
            tableMapping.ColumnMappings.Add ("nombre_departamento", "nombre_departamento");
            tableMapping.ColumnMappings.Add ("nombre_unidad", "nombre_unidad");
            tableMapping.ColumnMappings.Add ("nombre_suplidor", "nombre_suplidor");
            tableMapping.ColumnMappings.Add ("estado", "estado");
            this._adapter.TableMappings.Add (tableMapping);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitConnection () {
            this._connection = new global::System.Data.SqlClient.SqlConnection ();
            this._connection.ConnectionString = global::Inventario.Properties.Settings.Default.inventarioConnectionString;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitCommandCollection () {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand ();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "dbo.consultarVentas";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.StoredProcedure;
            this._commandCollection[0].Parameters.Add (new global::System.Data.SqlClient.SqlParameter ("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add (new global::System.Data.SqlClient.SqlParameter ("@numero_factura", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute ("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute (global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill (DataSet1.consultarVentasDataTable dataTable, global::System.Nullable<int> numero_factura) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((numero_factura.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[1].Value = ((int) (numero_factura.Value));
            } else {
                this.Adapter.SelectCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear ();
            }
            int returnValue = this.Adapter.Fill (dataTable);
            return returnValue;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute ("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute (global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual DataSet1.consultarVentasDataTable GetData (global::System.Nullable<int> numero_factura) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((numero_factura.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[1].Value = ((int) (numero_factura.Value));
            } else {
                this.Adapter.SelectCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            DataSet1.consultarVentasDataTable dataTable = new DataSet1.consultarVentasDataTable ();
            this.Adapter.Fill (dataTable);
            return dataTable;
        }
    }

    /// <summary>
    ///TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute ("code")]
    [global::System.ComponentModel.ToolboxItem (true)]
    [global::System.ComponentModel.DesignerAttribute ("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerDesigner, Microsoft.VSD" +
        "esigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute ("vs.data.TableAdapterManager")]
    public partial class TableAdapterManager : global::System.ComponentModel.Component {

        private UpdateOrderOption _updateOrder;

        private bool _backupDataSetBeforeUpdate;

        private global::System.Data.IDbConnection _connection;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public UpdateOrderOption UpdateOrder {
            get {
                return this._updateOrder;
            }
            set {
                this._updateOrder = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool BackupDataSetBeforeUpdate {
            get {
                return this._backupDataSetBeforeUpdate;
            }
            set {
                this._backupDataSetBeforeUpdate = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable (false)]
        public global::System.Data.IDbConnection Connection {
            get {
                if ((this._connection != null)) {
                    return this._connection;
                }
                return null;
            }
            set {
                this._connection = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable (false)]
        public int TableAdapterInstanceCount {
            get {
                int count = 0;
                return count;
            }
        }

        /// <summary>
        ///Update rows in top-down order.
        ///</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private int UpdateUpdatedRows (DataSet1 dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
            int result = 0;
            return result;
        }

        /// <summary>
        ///Insert rows in top-down order.
        ///</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private int UpdateInsertedRows (DataSet1 dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
            int result = 0;
            return result;
        }

        /// <summary>
        ///Delete rows in bottom-up order.
        ///</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private int UpdateDeletedRows (DataSet1 dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows) {
            int result = 0;
            return result;
        }

        /// <summary>
        ///Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first
        ///</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private global::System.Data.DataRow[] GetRealUpdatedRows (global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
            if (((updatedRows == null) ||
                    (updatedRows.Length < 1))) {
                return updatedRows;
            }
            if (((allAddedRows == null) ||
                    (allAddedRows.Count < 1))) {
                return updatedRows;
            }
            global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow> ();
            for (int i = 0;
                (i < updatedRows.Length); i = (i + 1)) {
                global::System.Data.DataRow row = updatedRows[i];
                if ((allAddedRows.Contains (row) == false)) {
                    realUpdatedRows.Add (row);
                }
            }
            return realUpdatedRows.ToArray ();
        }

        /// <summary>
        ///Update all changes to the dataset.
        ///</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public virtual int UpdateAll (DataSet1 dataSet) {
            if ((dataSet == null)) {
                throw new global::System.ArgumentNullException ("dataSet");
            }
            if ((dataSet.HasChanges () == false)) {
                return 0;
            }
            global::System.Data.IDbConnection workConnection = this.Connection;
            if ((workConnection == null)) {
                throw new global::System.ApplicationException ("TableAdapterManager contains no connection information. Set each TableAdapterMana" +
                    "ger TableAdapter property to a valid TableAdapter instance.");
            }
            bool workConnOpened = false;
            if (((workConnection.State & global::System.Data.ConnectionState.Broken) ==
                    global::System.Data.ConnectionState.Broken)) {
                workConnection.Close ();
            }
            if ((workConnection.State == global::System.Data.ConnectionState.Closed)) {
                workConnection.Open ();
                workConnOpened = true;
            }
            global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction ();
            if ((workTransaction == null)) {
                throw new global::System.ApplicationException ("The transaction cannot begin. The current data connection does not support transa" +
                    "ctions or the current state is not allowing the transaction to begin.");
            }
            global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow> ();
            global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow> ();
            global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> ();
            global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> ();
            int result = 0;
            global::System.Data.DataSet backupDataSet = null;
            if (this.BackupDataSetBeforeUpdate) {
                backupDataSet = new global::System.Data.DataSet ();
                backupDataSet.Merge (dataSet);
            }
            try {
                // ---- Prepare for update -----------
                //
                // 
                //---- Perform updates -----------
                //
                if ((this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)) {
                    result = (result + this.UpdateUpdatedRows (dataSet, allChangedRows, allAddedRows));
                    result = (result + this.UpdateInsertedRows (dataSet, allAddedRows));
                } else {
                    result = (result + this.UpdateInsertedRows (dataSet, allAddedRows));
                    result = (result + this.UpdateUpdatedRows (dataSet, allChangedRows, allAddedRows));
                }
                result = (result + this.UpdateDeletedRows (dataSet, allChangedRows));
                // 
                //---- Commit updates -----------
                //
                workTransaction.Commit ();
                if ((0 < allAddedRows.Count)) {
                    global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
                    allAddedRows.CopyTo (rows);
                    for (int i = 0;
                        (i < rows.Length); i = (i + 1)) {
                        global::System.Data.DataRow row = rows[i];
                        row.AcceptChanges ();
                    }
                }
                if ((0 < allChangedRows.Count)) {
                    global::System.Data.DataRow[] rows = new System.Data.DataRow[allChangedRows.Count];
                    allChangedRows.CopyTo (rows);
                    for (int i = 0;
                        (i < rows.Length); i = (i + 1)) {
                        global::System.Data.DataRow row = rows[i];
                        row.AcceptChanges ();
                    }
                }
            } catch (global::System.Exception ex) {
                workTransaction.Rollback ();
                // ---- Restore the dataset -----------
                if (this.BackupDataSetBeforeUpdate) {
                    global::System.Diagnostics.Debug.Assert ((backupDataSet != null));
                    dataSet.Clear ();
                    dataSet.Merge (backupDataSet);
                } else {
                    if ((0 < allAddedRows.Count)) {
                        global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
                        allAddedRows.CopyTo (rows);
                        for (int i = 0;
                            (i < rows.Length); i = (i + 1)) {
                            global::System.Data.DataRow row = rows[i];
                            row.AcceptChanges ();
                            row.SetAdded ();
                        }
                    }
                }
                throw ex;
            } finally {
                if (workConnOpened) {
                    workConnection.Close ();
                }
                if ((0 < adaptersWithAcceptChangesDuringUpdate.Count)) {
                    global::System.Data.Common.DataAdapter[] adapters = new System.Data.Common.DataAdapter[adaptersWithAcceptChangesDuringUpdate.Count];
                    adaptersWithAcceptChangesDuringUpdate.CopyTo (adapters);
                    for (int i = 0;
                        (i < adapters.Length); i = (i + 1)) {
                        global::System.Data.Common.DataAdapter adapter = adapters[i];
                        adapter.AcceptChangesDuringUpdate = true;
                    }
                }
            }
            return result;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected virtual void SortSelfReferenceRows (global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst) {
            global::System.Array.Sort<global::System.Data.DataRow> (rows, new SelfReferenceComparer (relation, childFirst));
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected virtual bool MatchTableAdapterConnection (global::System.Data.IDbConnection inputConnection) {
            if ((this._connection != null)) {
                return true;
            }
            if (((this.Connection == null) ||
                    (inputConnection == null))) {
                return true;
            }
            if (string.Equals (this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal)) {
                return true;
            }
            return false;
        }

        /// <summary>
        ///Update Order Option
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public enum UpdateOrderOption {

            InsertUpdateDelete = 0,

            UpdateInsertDelete = 1,
        }

        /// <summary>
        ///Used to sort self-referenced table's rows
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private class SelfReferenceComparer : object, global::System.Collections.Generic.IComparer<global::System.Data.DataRow> {

            private global::System.Data.DataRelation _relation;

            private int _childFirst;

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal SelfReferenceComparer (global::System.Data.DataRelation relation, bool childFirst) {
                this._relation = relation;
                if (childFirst) {
                    this._childFirst = -1;
                } else {
                    this._childFirst = 1;
                }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private global::System.Data.DataRow GetRoot (global::System.Data.DataRow row, out int distance) {
                global::System.Diagnostics.Debug.Assert ((row != null));
                global::System.Data.DataRow root = row;
                distance = 0;

                global::System.Collections.Generic.IDictionary<global::System.Data.DataRow, global::System.Data.DataRow> traversedRows = new global::System.Collections.Generic.Dictionary<global::System.Data.DataRow, global::System.Data.DataRow> ();
                traversedRows[row] = row;

                global::System.Data.DataRow parent = row.GetParentRow (this._relation, global::System.Data.DataRowVersion.Default);
                for (;
                    ((parent != null) &&
                        (traversedRows.ContainsKey (parent) == false));
                ) {
                    distance = (distance + 1);
                    root = parent;
                    traversedRows[parent] = parent;
                    parent = parent.GetParentRow (this._relation, global::System.Data.DataRowVersion.Default);
                }

                if ((distance == 0)) {
                    traversedRows.Clear ();
                    traversedRows[row] = row;
                    parent = row.GetParentRow (this._relation, global::System.Data.DataRowVersion.Original);
                    for (;
                        ((parent != null) &&
                            (traversedRows.ContainsKey (parent) == false));
                    ) {
                        distance = (distance + 1);
                        root = parent;
                        traversedRows[parent] = parent;
                        parent = parent.GetParentRow (this._relation, global::System.Data.DataRowVersion.Original);
                    }
                }

                return root;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Compare (global::System.Data.DataRow row1, global::System.Data.DataRow row2) {
                if (object.ReferenceEquals (row1, row2)) {
                    return 0;
                }
                if ((row1 == null)) {
                    return -1;
                }
                if ((row2 == null)) {
                    return 1;
                }

                int distance1 = 0;
                global::System.Data.DataRow root1 = this.GetRoot (row1, out distance1);

                int distance2 = 0;
                global::System.Data.DataRow root2 = this.GetRoot (row2, out distance2);

                if (object.ReferenceEquals (root1, root2)) {
                    return (this._childFirst * distance1.CompareTo (distance2));
                } else {
                    global::System.Diagnostics.Debug.Assert (((root1.Table != null) &&
                        (root2.Table != null)));
                    if ((root1.Table.Rows.IndexOf (root1) < root2.Table.Rows.IndexOf (root2))) {
                        return -1;
                    } else {
                        return 1;
                    }
                }
            }
        }
    }
}

#pragma warning restore 1591